=== ByOver03/C/Marcas_Nahuel/2n Trimestre/DTD2/Robert_Torrent_Nahuel_DTD2_5.dtd
<!ELEMENT listado (futuros+,divisas+,bonos+,letras+)>
<!ELEMENT futuros (producto, mercado?,(madrid|ny|frankfurt|tokyo))>
<!ELEMENT divisas (nombre, tipocambio+,(madrid|ny|frankfurt|tokyo))>
<!ELEMENT bonos (paisprocedencia, valorminimo, valormaximo, valordeseado, (madrid|ny|frankfurt|tokyo))>
<!ELEMENT letras (tipointeres, (espanya|eeuu|alemania|japon))>

<!ELEMENT producto (#PCDATA)>
<!ELEMENT mercado (#PCDATA)>
<!ELEMENT tipocambio (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT paisprocedencia (#PCDATA)>
<!ELEMENT valorminimo (#PCDATA)>
<!ELEMENT valormaximo (#PCDATA)>
<!ELEMENT valordeseado (#PCDATA)>
<!ELEMENT tipointeres (#PCDATA)>

<!ATTLIST futuros precio CDATA #REQUIRED>
<!ATTLIST divisas precio CDATA #REQUIRED>
<!ATTLIST bonos precio CDATA #REQUIRED>
<!ATTLIST letras precio CDATA #REQUIRED>
<!ATTLIST divisas estable (si|no) #IMPLIED >
<!ATTLIST bonos estable (si|no) #IMPLIED >

<!ELEMENT madrid EMPTY>
<!ELEMENT ny EMPTY>
<!ELEMENT frankfurt EMPTY>
<!ELEMENT tokyo EMPTY>
<!ELEMENT espanya EMPTY>
<!ELEMENT eeuu EMPTY>
<!ELEMENT alemania EMPTY>
<!ELEMENT japon EMPTY>

=== ByOver03/C/Marcas_Nahuel/2n Trimestre/DTD2/Robert_Torrent_Nahuel_DTD5.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE listado SYSTEM "../DTD2/Robert_Torrent_Nahuel_DTD2_5.dtd">

<listado>
    <futuros precio="5">
        <producto>tractor</producto>
        <mercado>nose</mercado>
        <madrid />
    </futuros>
    <divisas precio="5">
        <nombre>divisa1</nombre>
        <tipocambio>dolares</tipocambio>
        <ny />
    </divisas>
    <bonos precio="5">
        <paisprocedencia>alemania</paisprocedencia>
        <valorminimo>12</valorminimo>
        <valormaximo>20</valormaximo>
        <valordeseado>15</valordeseado>
        <frankfurt />
    </bonos>
    <letras precio="5">
        <tipointeres>alguno</tipointeres>
        <espanya />
    </letras>
</listado>
