=== ByOver03/C/Marcas_Nahuel/2n Trimestre/XSDII/Robert_Torrent_Nahuel_XSD2.5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleado" maxOccurs="unbounded" minOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="identificador" type="xs:int"/>
                            <xs:element name="fecha-inicio-contrato" type="xs:date"/>
                            <xs:element name="lugar-ocupa" type="xs:string"/>
                            <xs:element name="lugares-ocupados" type="xs:int"/>
                            <xs:element name="sueldo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="titulos-academicos" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="sede">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="Madrid" type="xs:string"/>
                                        <xs:element name="Barcelona" type="xs:string"/>
                                        <xs:element name="Valencia" type="xs:string"/>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Observaciones" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="meritos"></xs:element>
                                        <xs:element name="demeritos"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ByOver03/C/Marcas_Nahuel/2n Trimestre/XSDII/Robert_Torrent_Nahuel_XSD2.5.xml
<?xml version="1.0" encoding="UTF-8"?>
<Empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./Robert_Torrent_Nahuel_XSD2.5.xsd">
    <empleado>
        <nombre>Iker</nombre>
        <identificador>23321531</identificador>
        <fecha-inicio-contrato>2020-02-17</fecha-inicio-contrato>
        <lugar-ocupa>alguno</lugar-ocupa>
        <lugares-ocupados>1</lugares-ocupados>
        <sueldo>1254.21</sueldo>
        <titulos-academicos>ESO</titulos-academicos>
        <titulos-academicos>GM Informatica</titulos-academicos>
        <sede>
            <Barcelona/>
        </sede>
        <Observaciones>
            <meritos>ninguno</meritos>
            <demeritos>muchos</demeritos>
        </Observaciones>
    </empleado>
    <empleado>
        <nombre>Jose</nombre>
        <identificador>3215634</identificador>
        <fecha-inicio-contrato>2019-12-12</fecha-inicio-contrato>
        <lugar-ocupa>algun otro</lugar-ocupa>
        <lugares-ocupados>3</lugares-ocupados>
        <sueldo>1266.23</sueldo>
        <titulos-academicos>ESO</titulos-academicos>
        <sede>
            <Madrid/>
        </sede>
        <Observaciones>
            <meritos>muchos</meritos>
            <demeritos>pocos</demeritos>
        </Observaciones>
    </empleado>
    <empleado>
        <nombre>Nahuel</nombre>
        <identificador>54414351</identificador>
        <fecha-inicio-contrato>2019-10-30</fecha-inicio-contrato>
        <lugar-ocupa>alguno</lugar-ocupa>
        <lugares-ocupados>4</lugares-ocupados>
        <sueldo>1288.30</sueldo>
        <titulos-academicos>ESO</titulos-academicos>
        <sede>
            <Barcelona/>
        </sede>
    </empleado>
    <empleado>
        <nombre>Guiem</nombre>
        <identificador>42637485</identificador>
        <fecha-inicio-contrato>2020-06-18</fecha-inicio-contrato>
        <lugar-ocupa>alguno</lugar-ocupa>
        <lugares-ocupados>1</lugares-ocupados>
        <sueldo>1225.34</sueldo>
        <titulos-academicos>ESO</titulos-academicos>
        <sede>
            <Valencia/>
        </sede>
    </empleado>
    <empleado>
       <nombre>Sergi</nombre> 
       <identificador>531354</identificador>
       <fecha-inicio-contrato>2021-02-18</fecha-inicio-contrato>
       <lugar-ocupa>alguno</lugar-ocupa>
       <lugares-ocupados>1</lugares-ocupados>
       <sueldo>1225.34</sueldo>
       <titulos-academicos>ESO</titulos-academicos>
       <sede>
        <Valencia/>
       </sede>
    </empleado>
</Empresa>
